[package]
name = "scup"
version = "0.1.0"
edition = "2024"
description = "Git-like history with Syncthing-like automatic synchronization for large files"

[dependencies]
anyhow = "1"
async-trait = "0.1"
clap = "4.6.0"
ignore = "0.4.25"
kdam = "0.6.4"
postcard = { version = "1.1.3", features = ["use-std"] }
serde = { version = "1.0.228", features = ["derive"] }
russh = "0.44"
russh-keys = "0.44"
sha2 = "0.11.0"
tokio = { version = "1", features = ["full"] }
mdns-sd = "0.19.0"
rand = "0.8"
log = "0.4.29"
env_logger = "0.11.10"
derive_more = { version = "2.1.1", features = ["debug"] }
relative-path = "2.0.1"
